# ~/.config/hypr/modules/animations.conf -- animations
# see https://wiki.hypr.land/Configuring/Variables/#animations

# animations {
    # enabled = false
    # default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
    #        NAME,           X0,   Y0,   X1,   Y1
    # bezier = easeOutQuint,   0.23, 1,    0.32, 1
    # bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    # bezier = linear,         0,    0,    1,    1
    # bezier = almostLinear,   0.5,  0.5,  0.75, 1
    # bezier = quick,          0.15, 0,    0.1,  1

    # default animations, see https://wiki.hypr.land/Configuring/Animations/
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    # animation = global,        1,     10,    default
    # animation = border,        1,     5.39,  easeOutQuint
    # animation = windows,       1,     4.79,  easeOutQuint
    # animation = windowsIn,     1,     4.1,   easeOutQuint, popin 87%
    # animation = windowsOut,    1,     1.49,  linear,       popin 87%
    # animation = fadeIn,        1,     1.73,  almostLinear
    # animation = fadeOut,       1,     1.46,  almostLinear
    # animation = fade,          1,     3.03,  quick
    # animation = layers,        1,     3.81,  easeOutQuint
    # animation = layersIn,      1,     4,     easeOutQuint, fade
    # animation = layersOut,     1,     1.5,   linear,       fade
    # animation = fadeLayersIn,  1,     1.79,  almostLinear
    # animation = fadeLayersOut, 1,     1.39,  almostLinear
    # animation = workspaces,    1,     1.94,  almostLinear, fade
    # animation = workspacesIn,  1,     1.21,  almostLinear, fade
    # animation = workspacesOut, 1,     1.94,  almostLinear, fade
    # animation = zoomFactor,    1,     7,     quick
# }
# ref: https://github.com/end-4/dots-hyprland/blob/a2c164109061554ee11e6ee6806b29e7e8e89417/dots/.config/hypr/hyprland/general.conf (used as reference: animation{})
# Author(s): end-4 <97237370+end-4@users.noreply.github.com> & contributors
# License: GPLv3

animations {
    enabled = true
    # Curves
    bezier = expressiveFastSpatial, 0.42, 1.67, 0.21, 0.90
    bezier = expressiveSlowSpatial, 0.39, 1.29, 0.35, 0.98
    bezier = expressiveDefaultSpatial, 0.38, 1.21, 0.22, 1.00
    bezier = emphasizedDecel, 0.05, 0.7, 0.1, 1
    bezier = emphasizedAccel, 0.3, 0, 0.8, 0.15
    bezier = standardDecel, 0, 0, 0, 1
    bezier = menu_decel, 0.1, 1, 0, 1
    bezier = menu_accel, 0.52, 0.03, 0.72, 0.08
    bezier = stall, 1, -0.1, 0.7, 0.85
    # Configs
    # windows
    animation = windowsIn, 1, 3, emphasizedDecel, popin 80%
    animation = fadeIn, 1, 3, emphasizedDecel
    animation = windowsOut, 1, 2, emphasizedDecel, popin 90%
    animation = fadeOut, 1, 2, emphasizedDecel
    animation = windowsMove, 1, 3, emphasizedDecel, slide
    # animation = border, 1, 10, emphasizedDecel
    # layers
    animation = layersIn, 1, 2.7, emphasizedDecel, popin 93%
    animation = layersOut, 1, 2.4, menu_accel, popin 94%
    # fade
    animation = fadeLayersIn, 1, 0.5, menu_decel
    animation = fadeLayersOut, 1, 2.7, stall
    # workspaces
    animation = workspaces, 1, 7, menu_decel, slide
    ## specialWorkspace
    animation = specialWorkspaceIn, 1, 2.8, emphasizedDecel, slidevert
    animation = specialWorkspaceOut, 1, 1.2, emphasizedAccel, slidevert
    # zoom
    # animation = zoomFactor, 1, 3, standardDecel
}
