# ~/.config/hypr/modules/autostart.conf -- run on startup
# autostart necessary processes (like notifications daemons, status bars, etc.)

exec-once = hyprpm reload -nn && hyprctl dismissnotify
exec-once = hypridle
# system services
# exec-once = systemctl --user start xdg-desktop-portal-hyprland
exec-once = /usr/lib/xdg-desktop-portal-hyprland
# exec-once = systemctl --user start xdg-desktop-portal
exec-once = /usr/lib/xdg-desktop-portal -r
exec-once = gnome-keyring-daemon --start --components=secrets
# exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent0
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# display and wallpaper
#exec-once = awww-daemon
#exec-once = hyprctl setcursor Naroz 25 # set custom cursor (naroz)

# status bar and notifications
exec-once = waybar
exec-once = swaync

# network and bluetooth
exec-once = nm-applet --indicator
# exec-once = blueman-applet

# clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# other
exec-once = vicinae server --no-extension-runtime # raycast clone
