#!/bin/sh
exec 2>&1

# sshd wants to be started with absolute pathname
SSHD=$(which sshd) || sv down $(pwd)

exec "$SSHD" -D -e

# memory limits set by chpst are inherited to subprocesses,
# disabled by default
#exec chpst -m8000000 "$SSHD" -D -e
