#!/bin/sh
set -e

is_up () {
# stat --> run | down
if [ -e "/etc/sv/$name/supervise/stat" ]; then
	stat=$(cat "/etc/sv/$name/supervise/stat")
	if [ "$stat" != run ]; then
		return 1
	else
		return 0
	fi
else
	return 1
fi
}

case "$1" in
    purge|remove)
	for path in /etc/runit-services/purge-sv/* ; do
		name=$(basename "$path")
		enable=$(cat /etc/runit-services/purge-sv/"$name"/enable)
		onupgrade=$(cat /etc/runit-services/purge-sv/"$name"/onupgrade)
		if [ "$onupgrade" = 'nostop' ] || [ "$onupgrade" = 'reload' ]; then
			if is_up ; then
				#disable in runit will also stop the service
				if [ "$1" = 'remove' ]; then
					echo "warning: disabling $name is dangerous, skipping"
					echo "Please disable $name manually from a getty"
					continue
				else  #purge
					echo "error: failed to purge $name : still running"
					echo "please stop $name manually from a getty first"
					echo "then run 'dpkg -P runit-services' "
					exit 1
				fi
			fi
		fi
		if [ -e /lib/runit-helper/runit-helper ]; then
			NAME=$name ENABLE=$enable ONUPGRADE=$onupgrade \
				/lib/runit-helper/runit-helper postrm "$@"
		fi
		if [ "$1" = 'purge' ]; then
			rm -rf /etc/sv/"$name"
			rm -rf /etc/runit-services/purge-sv/"$name"
		fi
	done
    ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
