#!/bin/sh
set -e

is_up () {
# stat --> run | down
if [ -e "/etc/service/$name/supervise/stat" ]; then
	stat=$(cat "/etc/service/$name/supervise/stat")
	if [ "$stat" != run ]; then
		return 1
	else
		return 0
	fi
else
	return 1
fi
}

if [ "$1" = remove ]; then
	for path in  /etc/service/* ; do
		name=$(basename "$path")
		if [ -r /usr/share/runit/sv/"$name"/.meta/pkg ]; then
			# /usr/share/runit/sv/ is empty at postrm
			ispkg=$(cat /usr/share/runit/sv/"$name"/.meta/pkg)
			if [ "$ispkg" = 'runit-services' ]; then
				cp -r /usr/share/runit/sv/"$name"/.meta   "/etc/runit-services/purge-sv/$name"
			else
				continue # not from this package
			fi
		fi
		if [ -z "${DPKG_ROOT:-}" ] ; then
			ENABLE=yes #irrelevant for prerm
			if [ -r /etc/service/"$name"/.meta/onupgrade ]; then
				onupgrade=$(cat /etc/service/"$name"/.meta/onupgrade)
				if [ "$onupgrade" = "nostop" ] || [ "$onupgrade" = 'reload' ]; then
					if is_up ; then
						echo "warning: stop $name is dangerous, skipping"
						echo "Please stop $name manually from a getty"
					fi
					continue
				fi
			else
				onupgrade=restart #dh default
			fi
			NAME=$name ENABLE=yes ONUPGRADE=$onupgrade \
				/lib/runit-helper/runit-helper prerm "$@"
		fi
	done
fi

#DEBHELPER#

exit 0
