#!/bin/sh
set -e

is_up () {
# stat --> run | down
if [ -e "/etc/service/$name/supervise/stat" ]; then
	stat=$(cat "/etc/service/$name/supervise/stat")
	if [ "$stat" != run ]; then
		return 1
	else
		return 0
	fi
else
	return 1
fi
}

if [ "$1" = purge ]; then
	echo "/usr/share/runit/sv.now/runsvdir@user template may be in use"
	echo "warning: runsvdir@user not removed"
	# TODO: same problem as in prerm, can't remove a directory if the service is up
	# but stopping the user session could distrupt the upgrade
	# TODO: idea: send TERM to user rusnvdir service so that all runsvs are detached
	# and survive their runsvdir; then the rusnvdir@user template can be removed
fi




#DEBHELPER#

exit 0
