#!/bin/sh
set -e

case "$1" in
    configure)
	if [ ! -d /etc/runit/override-sysv.d ]; then
		mkdir -p /etc/runit/override-sysv.d #to be removed after runit-2.1.2-61 reaches oldstable
	fi
	if [ -z "${DPKG_ROOT:-}" ] ; then
		echo "sync runit services.."
		# this will copy and enable appropriate services
		/lib/runit/trigger_sv setup
		/lib/runit/trigger_sv upgrade
		echo ".. done"
	fi
    ;;
    triggered)
	if [ -f /etc/logrotate.d/rsyslog ] && [ ! -f /etc/logrotate.d/aa-rsyslog-runit ]; then
		if [ -f /etc/logrotate.d/aa-rsyslog-runit.disabled ]; then
			mv -f /etc/logrotate.d/aa-rsyslog-runit.disabled /etc/logrotate.d/aa-rsyslog-runit
		else
			cp /usr/share/runit-services/logrotate.d/aa-rsyslog-runit   /etc/logrotate.d/
		fi
	fi
	if [ -f /etc/logrotate.d/rsyslog.disabled ] && [ -f /etc/logrotate.d/aa-rsyslog-runit ]; then
		mv -f /etc/logrotate.d/aa-rsyslog-runit /etc/logrotate.d/aa-rsyslog-runit.disabled
	fi
    ;;
esac

#DEBHELPER#

exit 0
