#!/bin/sh
set -e

is_up () {
# stat --> run | down
if [ -e "/etc/service/$name/supervise/stat" ]; then
	stat=$(cat "/etc/service/$name/supervise/stat")
	if [ "$stat" != run ]; then
		return 1
	else
		return 0
	fi
else
	return 1
fi
}
failpurge=
case "$1" in
    purge|remove)
	for path in /etc/runit-services/purge-sv/* ; do
		name=$(basename "$path")
		if [ -r  /etc/runit-services/purge-sv/"$name"/enable ]; then
			enable=$(cat /etc/runit-services/purge-sv/"$name"/enable)
		else
			enable=yes  # dh implicit default
		fi
		if [ -r  /etc/runit-services/purge-sv/"$name"/onupgrade ]; then
			onupgrade=$(cat /etc/runit-services/purge-sv/"$name"/onupgrade)
			if [ "$onupgrade" = 'nostop' ] || [ "$onupgrade" = 'reload' ]; then
				if is_up ; then
					#disable in runit will also stop the service
					if [ "$1" = 'remove' ]; then
						echo "warning: disabling $name is dangerous, skipping"
						echo "Please disable $name manually from a getty"
						continue
					else  #purge
						echo "error: failed to purge $name : still running"
						echo "please disable $name manually from a getty first with"
						echo "update-service --remove /etc/sv/$name"
						echo "then run 'dpkg -P runit-services' "
						failpurge=1
						continue
					fi
				fi
			fi
		else
			onupgrade=restart # dh implicit default
		fi
		if [ -e /lib/runit-helper/runit-helper ]; then
			NAME=$name ENABLE=$enable ONUPGRADE=$onupgrade \
				/lib/runit-helper/runit-helper postrm "$@"
		fi
		if [ "$1" = 'purge' ]; then
			rm -rf /etc/sv/"$name"
			rm -rf /etc/runit-services/purge-sv/"$name"
		fi
	done
	if [ -n "$failpurge" ] ; then
		echo "for more details on how to purge this package read"
		echo "https://salsa.debian.org/Lorenzo.ru.g-guest/runit-services/-/blob/master/README"
		exit 1
	fi
    ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
