# src: https://github.com/end-4/dots-hyprland/blob/a2c164109061554ee11e6ee6806b29e7e8e89417/dots/.config/hypr/hypridle.conf
# Author(s): end-4 <97237370+end-4@users.noreply.github.com> & contributors
# License: GPLv3

$lock_cmd = ~/.config/qylock/quickshell-lockscreen/lock.sh
# $lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    # before_sleep_cmd = loginctl lock-session
    # after_sleep_cmd = hyprctl dispatch global quickshell:lockFocus
    # after_sleep_cmd = loginctl lock-session
    inhibit_sleep = 3
}

listener {
    timeout = 240
    on-timeout = loginctl lock-session
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 360
    on-timeout = $suspend_cmd
}
