#!/bin/sh
mkdir -p /var/cache/snooze
exec snooze -s 1d -t /var/cache/runit-snooze/daily -- sh -c \
	"test -d /etc/cron.daily && run-parts --lsbsysinit /etc/cron.daily; touch /var/cache/runit-snooze/daily"
