#!/bin/sh
mkdir -p /var/cache/snooze
exec snooze -H \* -s 1h -t /var/cache/runit-snooze/hourly -- sh -c \
	"test -d /etc/cron.hourly && run-parts --lsbsysinit /etc/cron.hourly; touch /var/cache/runit-snooze/hourly"
