#!/bin/sh

export XDG_RUNTIME_DIR=/run/user/$(id -u)

# Wait for the PipeWire daemon to start.
while [ ! -S "$XDG_RUNTIME_DIR/pipewire-0" ]; do
    sleep 0.1
done

[ -r ./conf ] && . ./conf

if [ "${LOGGING_ENABLE}x" = "1x" -a -n "${LOG_LEVEL}" ]; then
    export PIPEWIRE_DEBUG="${LOG_LEVEL}"
fi

exec pipewire-pulse ${OPTS:-} 2>&1
